#!/bin/bash

npx tailwindcss -i css/tailwind.css -o public/css/tailwind.css -c tailwind.config.js

while true; do
  inotifywait -e modify,create,delete -r . --exclude public && \
  #hugo --ignoreCache
  hugo
done
